# Generated by Django 5.1.5 on 2025-01-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesting_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('management_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='centers.management_center')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('management_center', 'name')},
            },
        ),
    ]
