# Generated by Django 5.1.5 on 2025-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_requesting_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='management_center',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesting_center',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
