# Generated by Django 5.1.5 on 2025-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_management_center_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management_center',
            options={'ordering': ['name'], 'verbose_name': 'Centro Gestor', 'verbose_name_plural': 'Centros Gestores'},
        ),
        migrations.AlterModelOptions(
            name='requesting_center',
            options={'ordering': ['name'], 'verbose_name': 'Centro Solicitante', 'verbose_name_plural': 'Centros Solicitantes'},
        ),
        migrations.AlterField(
            model_name='management_center',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesting_center',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
