# Generated by Django 5.1.5 on 2025-01-30 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_requesting_center_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_center',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_gertores_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='management_center',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_gestores_atualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
