# Generated by Django 5.1.5 on 2025-02-04 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('GRADUACAO', 'Graduação'), ('POS_GRADUACAO', 'Pós-Graduação'), ('AUXILIO_CHECHE_ESCOLA', 'Auxílio Creche Escola'), ('LINGUA_ESTRANGEIRA', 'Língua Estrangeira')], max_length=100, null=True, verbose_name='Tipo')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Total')),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('amount_per_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Parcela')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Início'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Assistência',
                'verbose_name_plural': 'Assistências',
                'ordering': ['start_date'],
            },
        ),
    ]
