# Generated by Django 5.1.5 on 2025-01-31 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgetline', '0009_alter_budgetlinemovement_movement_notes'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(choices=[('UNICO', 'Pagamento Único'), ('PARCELADO', 'Parcelado')], max_length=10)),
                ('type', models.CharField(blank=True, choices=[('GRADUACAO', 'Graduação'), ('POS_GRADUACAO', 'Pós-Graduação'), ('AUXILIO_CHECHE_ESCOLA', 'Auxílio Creche Escola'), ('LINGUA_ESTRANGEIRA', 'Língua Estrangeira')], max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_per_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Início'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=10)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='budgetline.budgetline')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Assistência',
                'verbose_name_plural': 'Assistências',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='aid.assistance')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date'],
            },
        ),
    ]
