# Generated by Django 5.1.5 on 2025-01-31 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_alter_assistance_amount_per_installment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='assistance_type',
        ),
        migrations.AddField(
            model_name='assistance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistance',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_assistances', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='updated_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='updated_assistances', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssistanceInstallment',
        ),
    ]
