# Generated by Django 5.1.5 on 2025-02-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.coordination')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sectors.direction')),
                ('management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.management')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
