# Generated by Django 5.1.5 on 2025-01-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('coordination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.coordination')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sectors.direction')),
                ('management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.management')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
