# Generated by Django 5.1.5 on 2025-01-31 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgetline', '0009_alter_budgetlinemovement_movement_notes'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(blank=True, editable=False, max_length=7, unique=True, verbose_name='Contrato')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('payment_nature', models.CharField(choices=[('PAGAMENTO ÚNICO', 'PAGAMENTO ÚNICO'), ('PAGAMENTO ANUAL', 'PAGAMENTO ANUAL'), ('PAGAMENTO SEMANAL', 'PAGAMENTO SEMANAL'), ('PAGAMENTO MENSAL', 'PAGAMENTO MENSAL'), ('PAGAMENTO QUIZENAL', 'PAGAMENTO QUINZENAL'), ('PAGAMENTO TRIMESTRAL', 'PAGAMENTO TRIMESTRAL'), ('PAGAMENTO SEMESTRAL', 'PAGAMENTO SEMESTRAL'), ('PAGAMENTO SOB DEMANDA', 'PAGAMENTO SOB DEMANDA')], max_length=30, verbose_name='Natureza do Pagamento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Original')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Atual')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='budgetline.budgetline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('main_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_main_inspector', to='employees.employee', verbose_name='Fiscal Principal')),
                ('substitute_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_substitute_inspector', to='employees.employee', verbose_name='Fiscal Substituto')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['protocol_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('ACRESCIMO_VALOR', 'Acréscimo de Valor'), ('REDUCAO_VALOR', 'Redução de Valor'), ('PRORROGACAO_PRAZO', 'Prorrogação de Prazo')], max_length=20, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('additional_term', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contrato', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
                'ordering': ['contract', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['contract', 'number'],
            },
        ),
    ]
