# Generated by Django 5.1.5 on 2025-02-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('ENCERRADO', 'ENCERRADO')], default='ATIVO', max_length=30, verbose_name='Status'),
        ),
    ]
