# Generated by Django 5.1.5 on 2025-02-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Último acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
    ]
