# Generated by Django 5.1.5 on 2025-01-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direção',
                'verbose_name_plural': 'Direções',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerencias', to='sectors.direction')),
            ],
            options={
                'verbose_name': 'Gerência',
                'verbose_name_plural': 'Gerências',
                'ordering': ['name'],
                'unique_together': {('direction', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes', to='sectors.management')),
            ],
            options={
                'verbose_name': 'Coordenação',
                'verbose_name_plural': 'Coordenações',
                'ordering': ['name'],
                'unique_together': {('management', 'name')},
            },
        ),
    ]
