# Generated by Django 5.1.5 on 2025-01-30 00:56

import budgets.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('centers', '0009_alter_management_center_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Disponível'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], max_length=5, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='management_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='centers.management_center', verbose_name='Centro Gestor'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(validators=[budgets.utils.validators.validate_year], verbose_name='Ano'),
        ),
    ]
