# Generated by Django 5.1.5 on 2025-01-30 01:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_rename_update_at_budget_updated_at_budget_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetmovement',
            options={'ordering': ['-movement_date'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AddField(
            model_name='budgetmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='budgetmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_movements_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='budgets.budget', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='movement_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data da Movimentação'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='budgets.budget', verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='budgetmovement',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
