# Generated by Django 5.1.5 on 2025-02-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgetline', '0001_initial'),
        ('budgets', '0001_initial'),
        ('centers', '0009_alter_management_center_created_at_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budgets.budget', verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='management_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='centers.management_center', verbose_name='Centro de Gestor'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='possible_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='possible_contract_fiscal', to='employees.employee', verbose_name='Fiscal Principal'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='requesting_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.requesting_center', verbose_name='Centro Solicitante'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='budgetlinemovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='budgetlinemovement',
            name='destination_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='budgetline.budgetline', verbose_name='Linha de Destino'),
        ),
        migrations.AddField(
            model_name='budgetlinemovement',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='budgetline.budgetline', verbose_name='Linha de Origem'),
        ),
        migrations.AddField(
            model_name='budgetlinemovement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_movements_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
