# Generated by Django 5.1.5 on 2025-01-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetline', '0003_budgetline_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetline',
            name='updated_by',
        ),
    ]
