# Generated by Django 5.1.5 on 2025-01-30 11:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetline', '0004_remove_budgetline_updated_by'),
        ('budgets', '0004_alter_budgetmovement_options_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budgets.budget', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='budgeted_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Orçado'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='category',
            field=models.CharField(blank=True, choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='contract_notes',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('DENTRO DO PRAZO', 'DENTRO DO PRAZO'), ('CONTRATADO NO PRAZO', 'CONTRATADO NO PRAZO'), ('CONTRATADO COM ATRASO', 'CONTRATADO COM ATRASO'), ('PRAZO VENCIDO', 'PRAZO VENCIDO'), ('LINHA TOTALMENTE REMANEJADA', 'LINHA TOTALMENTE REMANEJADA'), ('LINHA TOTALMENTE EXECUTADA', 'LINHA TOTALMENTE EXECUTADA'), ('LINHA DE PAGAMENTO', 'LINHA DE PAGAMENTO'), ('LINHA PARCIALMENTE REMANEJADA', 'LINHA PARCIALMENTE REMANEJADA'), ('LINHA PARCIALMENTE EXECUTADA', 'LINHA PARCIALMENTE EXECUTADA'), ('N/A', 'N/A')], max_length=100, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('SERVIÇO', 'SERVIÇO'), ('FORNECIMENTO', 'FORNECIMENTO'), ('ASSINATURA', 'ASSINATURA'), ('FORNECIMENTO/SERVIÇO', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='possible_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='possible_contract_fiscal', to='employees.employee', verbose_name='Fiscal Principal'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='probable_procurement_type',
            field=models.CharField(choices=[('LICITAÇÃO', 'LICITAÇÃO'), ('DISPENSA EM RAZÃO DO VALOR', 'DISPENSA EM RAZÃO DO VALOR'), ('CONVÊNIO', 'CONVÊNIO'), ('FUNDO FIXO', 'FUNDO FIXO'), ('INEXIGIBILIDADE', 'INEXIGIBILIDADE'), ('ATA DE REGISTRO DE PREÇO', 'ATA DE REGISTRO DE PREÇO'), ('ACORDO DE COOPERAÇÃO', 'ACORDO DE COOPERAÇÃO'), ('APOSTILAMENTO', 'APOSTILAMENTO')], max_length=100, verbose_name='Tipo de Aquisição'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='process_status',
            field=models.CharField(blank=True, choices=[('VENCIDO', 'VENCIDO'), ('DENTRO DO PRAZO', 'DENTRO DO PRAZO'), ('ELABORADO COM ATRASO', 'ELABORADO COM ATRASO'), ('ELABORADO NO PRAZO', 'ELABORADO NO PRAZO')], max_length=100, null=True, verbose_name='Status do Processo'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
