# Generated by Django 5.1.5 on 2025-01-30 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetline', '0005_budgetline_created_by_budgetline_updated_by_and_more'),
        ('centers', '0009_alter_management_center_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetline',
            options={'ordering': ['-created_at'], 'verbose_name': 'Linha Orçamentária', 'verbose_name_plural': 'Linhas Orçamentárias'},
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='managing_cost_center',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='requesting_cost_center',
        ),
        migrations.AddField(
            model_name='budgetline',
            name='management_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='centers.management_center', verbose_name='Centro de Gestor'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='requesting_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.requesting_center', verbose_name='Centro Solicitante'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='budget_classification',
            field=models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO'), ('N/A', 'N/A')], max_length=100, null=True, verbose_name='Classificação Orçamentária'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='expense_type',
            field=models.CharField(choices=[('Base Principal', 'Base Principal'), ('Serviços Especializados', 'Serviços Especializados'), ('Despesas Compartilhadas', 'Despesas Compartilhadas')], max_length=100, verbose_name='Tipo de Despesa'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='object',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Objeto'),
        ),
        migrations.CreateModel(
            name='BudgetLineMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(verbose_name='Data da Movimentação')),
                ('movement_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor da Movimentação')),
                ('movement_notes', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destination_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='budgetline.budgetline', verbose_name='Linha de Destino')),
                ('source_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='budgetline.budgetline', verbose_name='Linha de Origem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_movements_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimentação de Linha Orçamentária',
                'verbose_name_plural': 'Movimentações de Linha Orçamentária',
                'ordering': ['-movement_date'],
            },
        ),
    ]
