# Generated by Django 5.1.5 on 2025-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetline', '0008_alter_budgetlinemovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlinemovement',
            name='movement_notes',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Motivo'),
        ),
    ]
